#pragma once

#include <Fuse.iOS.UIControlCallback.h>
#include <iOS.CoreImage.CIImage.h>
#include <iOS.CoreLocation.CLBeaconRegion.h>
#include <iOS.CoreLocation.CLHeading.h>
#include <iOS.CoreLocation.CLLocation.h>
#include <iOS.CoreLocation.CLLocationManager.h>
#include <iOS.CoreLocation.CLRegion.h>
#include <iOS.CoreLocation.CLVisit.h>
#include <iOS.Foundation.NSArray.h>
#include <iOS.Foundation.NSAttributedString.h>
#include <iOS.Foundation.NSBundle.h>
#include <iOS.Foundation.NSDate.h>
#include <iOS.Foundation.NSDictionary.h>
#include <iOS.Foundation.NSError.h>
#include <iOS.Foundation.NSMutableArray.h>
#include <iOS.Foundation.NSMutableAttributedString.h>
#include <iOS.Foundation.NSMutableDictionary.h>
#include <iOS.Foundation.NSNumber.h>
#include <iOS.Foundation.NSObject.h>
#include <iOS.Foundation.NSSet.h>
#include <iOS.Foundation.NSString.h>
#include <iOS.Foundation.NSURL.h>
#include <iOS.Foundation.NSURLCache.h>
#include <iOS.Foundation.NSURLRequest.h>
#include <iOS.Foundation.NSValue.h>
#include <iOS.GLKit.GLKView.h>
#include <iOS.JavaScriptCore.JSContext.h>
#include <iOS.JavaScriptCore.JSValue.h>
#include <iOS.MapKit.MKMapView.h>
#include <iOS.OpenGLES.EAGLContext.h>
#include <iOS.OpenGLES.EAGLSharegroup.h>
#include <iOS.QuartzCore.CALayer.h>
#include <iOS.QuartzCore.CAShapeLayer.h>
#include <iOS.UIKit.NSLayoutManager.h>
#include <iOS.UIKit.NSMutableParagraphStyle.h>
#include <iOS.UIKit.NSParagraphStyle.h>
#include <iOS.UIKit.NSTextAttachment.h>
#include <iOS.UIKit.NSTextContainer.h>
#include <iOS.UIKit.NSTextStorage.h>
#include <iOS.UIKit.UIApplication.h>
#include <iOS.UIKit.UIBezierPath.h>
#include <iOS.UIKit.UIButton.h>
#include <iOS.UIKit.UIColor.h>
#include <iOS.UIKit.UIControl.h>
#include <iOS.UIKit.UIEvent.h>
#include <iOS.UIKit.UIFont.h>
#include <iOS.UIKit.UIImage.h>
#include <iOS.UIKit.UIImagePickerController.h>
#include <iOS.UIKit.UIImageView.h>
#include <iOS.UIKit.UILabel.h>
#include <iOS.UIKit.UINavigationController.h>
#include <iOS.UIKit.UIResponder.h>
#include <iOS.UIKit.UIScrollView.h>
#include <iOS.UIKit.UISlider.h>
#include <iOS.UIKit.UISwitch.h>
#include <iOS.UIKit.UITextField.h>
#include <iOS.UIKit.UITextPosition.h>
#include <iOS.UIKit.UITextRange.h>
#include <iOS.UIKit.UITextView.h>
#include <iOS.UIKit.UITouch.h>
#include <iOS.UIKit.UIView.h>
#include <iOS.UIKit.UIViewController.h>
#include <iOS.UIKit.UIWindow.h>
#include <iOS.WebKit.WKNavigation.h>
#include <iOS.WebKit.WKWebView.h>
